# Generated by Django 6.0.3 on 2026-06-06 10:01

import uuid

from django.db import migrations, models

import backupgram.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "base_url",
                    models.URLField(help_text="REST API base, e.g. https://host:8081"),
                ),
                (
                    "token",
                    backupgram.fields.EncryptedTextField(
                        help_text="Admin bearer token (stored encrypted)."
                    ),
                ),
                ("verify_tls", models.BooleanField(default=True)),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30, help_text="Request timeout (seconds)."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
